<li>
                                                        <a href="[field:arcurl/]" target="_blank" title="[field:title/]"><img src="[field:picname/]" alt="[field:title /]"/></a>
                                                        <div class="lr_r">
                                                            <span class="title "><a href="[field:arcurl /]" target="_blank" title="">[field:title /]</a></span>
                                                            <div class="txt"><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:description function="cn_substr(@me,80)"/]...</a><a href="[field:arcurl /]" target="_blank" title="[field:title function='htmlspecialchars(@me)'/] " style="color:red" >详细</a></div>
                                                        </div>
                                                    </li>