<?php
$z[0]=Array("arcurl","",71,86);
$z[1]=Array("title","",111,125);
$z[2]=Array("picname","",137,153);
$z[3]=Array("title","",160,175);
$z[4]=Array("arcurl","",350,366);
$z[5]=Array("title","",393,408);
$z[6]=Array("arcurl","",507,522);
$z[7]=Array("title","",547,561);
$z[8]=Array("description","",563,612);
$z[8][4]['function']="cn_substr(@me,80)";
$z[9]=Array("arcurl","",628,644);
$z[10]=Array("title","",669,716);
$z[10][4]['function']="htmlspecialchars(@me)";

?>