<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",14656,14681);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n    \r\n    <li style=\"width:16.66%;z-index:2;\"  class=\"wp_subtop\"  pid=\"72\" >\r\n    <a class=\"  \"  href=\"[field:typelink/]\" tytle=\"[field:typename/]\">\r\n    <span style=\"display:block;overflow:hidden;\">[field:typename/]</span>\r\n    </a>\r\n    </li>\r\n      ",14803,15334);
$z[2][4]['type']="top";
$z[2][4]['row']="8";
$z[2][4]['currentstyle']="<li style=";
$z[2][4]['width:16.66%;z-index:2;" class']="wp_subtop";
$z[2][4]['pid']="72";
$z[2][4]['> <a class']="";
$z[2][4]['href']="~typelink~";
$z[2][4]['tytle']="~typename~";
$z[2][4]['> <span style']="display:block;overflow:hidden;";
$z[2][4]['>~typename~</span> </a> </li>"']="";
$z[3]=Array("include","",16774,16818);
$z[3][4]['filename']="list_wenzhang.htm";

?>